spring:
  application:
    name: zooshop-config-server
  cloud:
    config:
      server:
        git:
          uri: ${CONFIG_REPO:https://github.com/bogomolov-a-a/spring-cloud-application-config-repo.git}
          default-label: ${CONFIG_REPO_DEFAULT_LABEL:master}
          search-paths: {application}
eureka:
  client:
    enabled: true
    register-with-eureka: true
    service-url:
      defaultZone: ${EUREKA_URI:http://localhost:8100/eureka}
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    logfile:
      enabled: true
    metrics:
      enabled: true
    health:
      enabled: true
    info:
      enabled: true
    env:
      enabled: true
server:
  forward-headers-strategy: FRAMEWORK
  port: 8888