spring:
  main:
    allow-circular-references: true
  batch:
    job:
      enabled: true
    jdbc:
      initialize-schema: always
      table-prefix: batch_
  shell:
    interactive:
      enabled: false
  datasource:
    url: jdbc:h2:mem:library
    username: sa
    password: sa
  data:
    mongodb:
      auto-index-creation: true
      database: homework14
      port: 27017
  mongodb:
    embedded:
      version: 5.0.5
  jpa:
    hibernate:
      ddl-auto: validate
  liquibase:
    change-log: db/db-change-log-master.xml
    contexts: production
