spring:
  config:
    import: ${CONFIG_SERVER_URL:configserver:http://localhost:8888}
  liquibase:
    change-log: /db/db.changelog-master.xml
  datasource:
    url: jdbc:h2:mem:customers
    username: sa
    password: sa
  h2:
    console:
      enabled: false
  jpa:
    hibernate:
      ddl-auto: validate